/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLogsRouteImport } from './routes/_admin/logs'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminWebRouteImport } from './routes/_admin/web'
import { Route as AdminCollectionsIndexRouteImport } from './routes/_admin/collections/index'
import { Route as AdminCollectionsCollectionNameRouteImport } from './routes/_admin/collections/$collectionName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebRoute = AdminWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsCollectionNameRoute =
  AdminCollectionsCollectionNameRouteImport.update({
    id: '/collections/$collectionName',
    path: '/collections/$collectionName',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/logs': typeof AdminLogsRoute
  '/settings': typeof AdminSettingsRoute
  '/web': typeof AdminWebRoute
  '/collections/$collectionName': typeof AdminCollectionsCollectionNameRoute
  '/collections/': typeof AdminCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/logs': typeof AdminLogsRoute
  '/settings': typeof AdminSettingsRoute
  '/web': typeof AdminWebRoute
  '/collections/$collectionName': typeof AdminCollectionsCollectionNameRoute
  '/collections': typeof AdminCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_admin/logs': typeof AdminLogsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/web': typeof AdminWebRoute
  '/_admin/collections/$collectionName': typeof AdminCollectionsCollectionNameRoute
  '/_admin/collections/': typeof AdminCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/logs'
    | '/settings'
    | '/web'
    | '/collections/$collectionName'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/logs'
    | '/settings'
    | '/web'
    | '/collections/$collectionName'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/demo'
    | '/login'
    | '/_admin/logs'
    | '/_admin/settings'
    | '/_admin/web'
    | '/_admin/collections/$collectionName'
    | '/_admin/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/logs': {
      id: '/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/web': {
      id: '/_admin/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof AdminWebRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/collections/': {
      id: '/_admin/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/collections/$collectionName': {
      id: '/_admin/collections/$collectionName'
      path: '/collections/$collectionName'
      fullPath: '/collections/$collectionName'
      preLoaderRoute: typeof AdminCollectionsCollectionNameRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWebRoute: typeof AdminWebRoute
  AdminCollectionsCollectionNameRoute: typeof AdminCollectionsCollectionNameRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWebRoute: AdminWebRoute,
  AdminCollectionsCollectionNameRoute: AdminCollectionsCollectionNameRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
