[package]
name = "herta_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hertabase"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
herta_api = { path = "../herta_api" }
herta_core = { path = "../herta_core" }
herta_db = { path = "../herta_db" }
rust-embed.workspace = true
salvo.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
