[package]
name = "herta_db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
email_address.workspace = true
futures-util.workspace = true
herta_core = { path = "../herta_core" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
surrealdb.workspace = true
surrealdb-core.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
