[package]
name = "herta_api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
futures-util.workspace = true
herta_auth = { path = "../herta_auth" }
herta_core = { path = "../herta_core" }
herta_db = { path = "../herta_db" }
herta_storage = { path = "../herta_storage" }
mime.workspace = true
mime-infer.workspace = true
salvo.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
http-body-util = "0.1.3"
tokio.workspace = true
