[package]
name = "herta_api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
herta_core = { path = "../herta_core" }
herta_db = { path = "../herta_db" }
salvo.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true

